In [1]:
import pickle
import numpy as np


In [2]:
from sklearn.metrics.pairwise import cosine_distances
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
import os
#os.listdir('./')

In [7]:
from tqdm.auto import tqdm

In [36]:
with open('lang8_embed_1_large.pickle', 'rb') as f:
    embd_1 = pickle.load(f)

with open('lang8_embed_2_large.pickle', 'rb') as f:
    embd_2 = pickle.load(f)

In [51]:
embd_1[3]

array([ 0.27738255,  0.65703076, -0.72234243, ...,  0.05797462,
        0.03212628,  0.4993575 ], dtype=float32)

In [52]:
embd_2[3]

array([ 0.1937528 ,  0.6885597 , -0.79130626, ...,  0.1501977 ,
       -0.00215527,  0.59284717], dtype=float32)

In [53]:
cosine_similarity([embd_2[3]],[embd_1[3]])[0,0]

0.9925745

In [58]:
cos_sim2 = []
for i in tqdm(range(len(embd_1))):
    cos_sim2.append(cosine_similarity([embd_2[i]],[embd_1[i]])[0,0])

In [60]:
cos_sim2[1]

0.99315935

In [56]:
cos_sim[1]

0.9999997

In [38]:
cos_sim = []
for lst1,lst2 in chunks(embd_1, embd_2, n=500):
    cos_sim.extend(process_chunks(lst1, lst2))

In [57]:
#cos_sim = np.array(cos_sim)

In [32]:
cos_sim.min()

0.7493959

In [33]:
cos_sim.max()

0.99135315

In [34]:
cos_sim.mean()

0.9750056

In [40]:
with open("lang8_cos_large.pickle", "wb") as f:
    pickle.dump(cos_sim, f)

In [54]:
cos_sim.min()

0.9999987

In [42]:
cos_sim.max()

1.0000014

In [23]:
import numpy as np
A=np.array([[2,2,3]])
B=np.array([[1,5,2],[6,6,4],[1,10,7],[5,8,2],[3,0,6]])

def csm(A,B):
    num=np.dot(A,B.T)
    p1=np.linalg.norm(A,axis=1)[:,np.newaxis]
    p2=np.linalg.norm(B,axis=1)[np.newaxis,:]
    return num/(p1*p2)

print(csm(A,B))

[[0.7970534  0.93075784 0.85152689 0.80479273 0.86772183]]
